import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useState } from 'react';
import styles from '@/styles/Home.module.css'
import styles2 from '@/styles/gen.module.css'

export default function App({ Component, pageProps }: AppProps) {
  const [password, setPassword ] = useState('')
  const [valid, setValid] = useState(false)
  const handleChange = (event: any) => {
    setPassword(event.target.value);
  };

  async function handleSubmit(event: any){
    event.preventDefault();
    const res = await fetch("/api/valid", {
      method: "POST",
      headers: {
        "Content-type": "application/json",
      },
      body: JSON.stringify({
        password
      }),
    });
    const data = await res.json()
    console.log(data)
    const valid = data['valid']
    setValid(valid)
    if(!valid){
      alert('Invalid Password :(')
    } else {
      alert('Welcome !')
    }
  }
  return (
    <div>
      <Head>
        <title>Love you Sarah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!valid && <main className={styles.main}>
        <form onSubmit={handleSubmit} className={styles2.textareaWrapper}>
          <label htmlFor="password" className={styles2.textareaLabel}>Password:</label>
          <input
            className={styles2.textareaInput}
            type="password"
            id="password"
            name="password"
            value={password}
            onChange={handleChange}
          />
          <button className={styles2.submitButton} type="submit">Submit</button>
        </form>

      </main>}
      {valid && <Component {...pageProps} />}
    </div>
  )
}
